# Generated by Django 3.2.12 on 2022-03-14 06:05

import apps.external_apps.qr.signals
import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogoForQRGeneratorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('company_name', models.CharField(max_length=100, verbose_name='Company Name')),
                ('logo_img', models.ImageField(upload_to=apps.external_apps.qr.signals.logo_directory_path, verbose_name='Logo')),
                ('default_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Company Logo',
                'verbose_name_plural': 'Companys Logos',
                'ordering': ['default_order'],
            },
        ),
        migrations.CreateModel(
            name='URLQRGeneratorWithLogoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('url_or_text', models.CharField(max_length=100, verbose_name='URL')),
                ('file_name', models.SlugField(default='qr', max_length=100, verbose_name='File Name')),
                ('description', ckeditor.fields.RichTextField(blank=True, verbose_name='Description')),
                ('qr_color', models.CharField(default='black', max_length=7, verbose_name='QR Color')),
                ('back_color', models.CharField(default='white', max_length=7, verbose_name='Back Color')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to=apps.external_apps.qr.signals.qr_directory_path, verbose_name='QR Image')),
                ('default_order', models.PositiveIntegerField(default=0)),
                ('logo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qr.logoforqrgeneratormodel')),
            ],
            options={
                'verbose_name': 'QR with Logo',
                'verbose_name_plural': 'QRs with Logo',
                'ordering': ['default_order'],
            },
        ),
    ]
