# Generated by Django 3.2.12 on 2022-03-14 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='logoforqrgeneratormodel',
            table='external_app_company_logo_for_qr',
        ),
    ]
