# Generated by Django 3.2.12 on 2022-03-14 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0002_alter_logoforqrgeneratormodel_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='urlqrgeneratorwithlogomodel',
            table='external_app_qr_with_logo',
        ),
    ]
