# Generated by Django 3.2.12 on 2022-03-17 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0003_alter_urlqrgeneratorwithlogomodel_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlqrgeneratorwithlogomodel',
            name='pepito',
            field=models.CharField(default='pepito', max_length=50),
        ),
    ]
