# Generated by Django 3.2.12 on 2022-03-23 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qr', '0004_urlqrgeneratorwithlogomodel_pepito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urlqrgeneratorwithlogomodel',
            name='pepito',
        ),
    ]
